'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'th';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'common.search': 'Search anything...',
    'common.logout': 'Logout',
    'common.filter': 'Filter',
    'common.export': 'Export Report',
    'common.all': 'All',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.time': 'Date/Time',
    'common.amount': 'Amount',
    'common.actions': 'Actions',
    'common.showing': 'Showing',
    'common.of': 'of',
    'common.items': 'items',
    'common.total': 'Total',
    'common.note': 'Note',
    'common.approvedBy': 'Approved By',
    'common.bank': 'Bank',
    'common.account': 'Account',
    'common.from': 'From',
    'common.to': 'To',
    
    // Status
    'status.completed': 'Completed',
    'status.pending': 'Pending',
    'status.failed': 'Failed',
    'status.all': 'All Status',
    
    // Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.analytics': 'Analytics',
    'sidebar.dataManagement': 'Data Management',
    'sidebar.manageWebsites': 'Manage Websites',
    'sidebar.manageBanks': 'Manage Banks',
    'sidebar.manageEmployees': 'Manage Employees',
    'sidebar.manageSalaryBase': 'Salary Base',
    'sidebar.manageLineTokens': 'Manage LINE Tokens',
    'sidebar.reports': 'Reports',
    'sidebar.products': 'Products',
    'sidebar.permissions': 'Permissions',
    'sidebar.dataChat': 'Data Chat',
    'sidebar.manageUsers': 'Manage Users',
    'sidebar.settings': 'Settings',
    'sidebar.help': 'Help',
    'sidebar.dailySummary': 'Daily Summary',
    'sidebar.cashWithdrawal': 'Cash Withdrawal',
    'sidebar.transfer': 'Transfer',
    'sidebar.dailyBalance': 'Daily Balance',
    'sidebar.expenses': 'Expenses',
    'sidebar.salaries': 'Salaries',
    
    // Data Management - Websites
    'websites.title': 'Manage Websites',
    'websites.subtitle': 'Website Management',
    'websites.addNew': 'Add Website',
    'websites.id': 'ID',
    'websites.name': 'Website Name',
    'websites.url': 'URL',
    'websites.status': 'Status',
    'websites.active': 'Active',
    'websites.inactive': 'Inactive',
    'websites.searchPlaceholder': 'Search websites...',
    
    // Data Management - Banks
    'banks.title': 'Manage Banks',
    'banks.subtitle': 'Bank Account Management',
    'banks.addNew': 'Add Bank',
    'banks.id': 'ID',
    'banks.type': 'Type',
    'banks.bank': 'Bank',
    'banks.deposit': 'Deposit',
    'banks.withdrawal': 'Withdrawal',
    'banks.payment': 'Payment',
    'banks.hold': 'Hold',
    'banks.accountName': 'Account Name',
    'banks.accountNumber': 'Account Number',
    'banks.status': 'Status',
    'banks.active': 'Active',
    'banks.inactive': 'Inactive',
    'banks.searchPlaceholder': 'Search banks...',
    'banks.allTypes': 'All Types',
    'banks.allStatus': 'All Status',
    
    // Data Management - Employees
    'employees.title': 'Manage Employees',
    'employees.subtitle': 'Employee Management',
    'employees.addNew': 'Add Employee',
    'employees.id': 'ID',
    'employees.website': 'Website',
    'employees.websites': 'Websites',
    'employees.fullName': 'Full Name',
    'employees.position': 'Position',
    'employees.receivingAccount': 'Receiving Account',
    'employees.accountName': 'Account Name',
    'employees.accountNumber': 'Account Number',
    'employees.bank': 'Bank',
    'employees.status': 'Status',
    'employees.active': 'Active',
    'employees.inactive': 'Inactive',
    'employees.searchPlaceholder': 'Search employees...',
    'employees.allWebsites': 'All Websites',
    'employees.allStatus': 'All Status',
    'employees.total': 'Total',
    'employees.notLinked': 'Not linked',
    
    // Data Management - Salary Base
    'salaryBase.title': 'Salary Base',
    'salaryBase.subtitle': 'Position & Salary Management',
    'salaryBase.addNew': 'Add Position',
    'salaryBase.position': 'Position',
    'salaryBase.baseSalary': 'Base Salary',
    'salaryBase.positionAllowance': 'Position Allowance',
    'salaryBase.totalCompensation': 'Total Compensation',
    'salaryBase.searchPlaceholder': 'Search position...',
    'salaryBase.totalPositions': 'Total Positions',
    'salaryBase.avgSalary': 'Average Salary',
    'salaryBase.maxSalary': 'Highest Salary',
    
    // Data Management - LINE Tokens
    'lineTokens.title': 'Manage LINE Tokens',
    'lineTokens.subtitle': 'LINE OA Token Management',
    'lineTokens.addNew': 'Add Token',
    'lineTokens.totalTokens': 'Total Tokens',
    'lineTokens.active': 'Active',
    'lineTokens.inactive': 'Inactive',
    'lineTokens.expired': 'Expired',
    'lineTokens.tokenName': 'Token Name',
    'lineTokens.channelId': 'Channel ID',
    'lineTokens.token': 'Access Token',
    'lineTokens.website': 'Website',
    'lineTokens.lastUsed': 'Last Used',
    'lineTokens.searchPlaceholder': 'Search tokens...',
    
    // Daily Summary
    'dailySummary.title': 'Daily Summary',
    'dailySummary.subtitle': 'Daily Summary Report',
    'dailySummary.totalRevenue': 'Total Revenue',
    'dailySummary.orders': 'Orders',
    'dailySummary.customers': 'Customers',
    'dailySummary.avgOrder': 'Average Order Value',
    'dailySummary.hourlyRevenue': 'Hourly Revenue',
    'dailySummary.topProducts': 'Top Products',
    'dailySummary.product': 'Product',
    'dailySummary.sales': 'Sales',
    'dailySummary.revenue': 'Revenue',
    'dailySummary.vsYesterday': 'vs yesterday',
    
    // Cash Withdrawal
    'cashWithdrawal.title': 'Cash Withdrawal',
    'cashWithdrawal.subtitle': 'Cash Withdrawal Report',
    'cashWithdrawal.totalWithdrawals': 'Total Withdrawals',
    'cashWithdrawal.completed': 'Completed',
    'cashWithdrawal.pending': 'Pending',
    'cashWithdrawal.failed': 'Failed',
    'cashWithdrawal.transactionId': 'Transaction ID',
    'cashWithdrawal.searchPlaceholder': 'Search transaction, bank...',
    
    // Transfer
    'transfer.title': 'Money Transfer',
    'transfer.subtitle': 'Money Transfer Report',
    'transfer.totalTransfers': 'Total Transfers',
    'transfer.transactionCount': 'Transactions',
    'transfer.pending': 'Pending',
    'transfer.todayTransfers': 'Today\'s Transfers',
    'transfer.transactionId': 'Transaction ID',
    'transfer.fromAccount': 'From Account',
    'transfer.toAccount': 'To Account',
    'transfer.searchPlaceholder': 'Search transaction, note...',
    
    // Daily Balance
    'dailyBalance.title': 'Daily Balance',
    'dailyBalance.subtitle': 'Daily Balance Report',
    'dailyBalance.totalBalance': 'Total Balance',
    'dailyBalance.todayDeposits': 'Today\'s Deposits',
    'dailyBalance.todayWithdrawals': 'Today\'s Withdrawals',
    'dailyBalance.netChange': 'Net Change',
    'dailyBalance.currentBalance': 'Current Balance',
    'dailyBalance.openingBalance': 'Opening Balance',
    'dailyBalance.deposits': 'Deposits',
    'dailyBalance.withdrawals': 'Withdrawals',
    'dailyBalance.transfers': 'Transfers',
    'dailyBalance.closingBalance': 'Closing Balance',
    'dailyBalance.allBanks': 'All Banks',
    'dailyBalance.noteTitle': 'Note',
    'dailyBalance.noteText': 'Balance is updated automatically every 15 minutes. Data may have slight discrepancies. Please verify actual balance from the banking system.',
    
    // Expenses
    'expenses.title': 'Expenses',
    'expenses.subtitle': 'Expense Report',
    'expenses.totalExpenses': 'Total Expenses',
    'expenses.pending': 'Pending Approval',
    'expenses.approved': 'Approved',
    'expenses.rejected': 'Rejected',
    'expenses.category': 'Category',
    'expenses.description': 'Description',
    'expenses.requestedBy': 'Requested By',
    'expenses.searchPlaceholder': 'Search expenses...',
    'expenses.office': 'Office Supplies',
    'expenses.travel': 'Travel',
    'expenses.utilities': 'Utilities',
    'expenses.marketing': 'Marketing',
    'expenses.equipment': 'Equipment',
    'expenses.other': 'Other',
    
    // Payroll
    'payroll.title': 'Payroll',
    'payroll.subtitle': 'Employee Payroll Report',
    'payroll.totalPayroll': 'Total Payroll',
    'payroll.totalEmployees': 'Total Employees',
    'payroll.paid': 'Paid',
    'payroll.pending': 'Pending',
    'payroll.employeeId': 'Employee ID',
    'payroll.employeeName': 'Employee Name',
    'payroll.department': 'Department',
    'payroll.position': 'Position',
    'payroll.baseSalary': 'Base Salary',
    'payroll.bonus': 'Bonus',
    'payroll.deductions': 'Deductions',
    'payroll.netSalary': 'Net Salary',
    'payroll.paymentDate': 'Payment Date',
    'payroll.searchPlaceholder': 'Search employee...',
    'payroll.allDepartments': 'All Departments',
    'payroll.accounting': 'Accounting',
    'payroll.sales': 'Sales',
    'payroll.it': 'IT',
    'payroll.hr': 'HR',
    'payroll.operations': 'Operations',
    
    // Data Chat
    'dataChat.title': 'Data Chat',
    'dataChat.subtitle': 'Customer Chat Management',
    'dataChat.searchPlaceholder': 'Search...',
    'dataChat.all': 'All',
    'dataChat.unread': 'Unread',
    'dataChat.pinned': 'Pinned',
    'dataChat.archived': 'Archived',
    'dataChat.spam': 'Spam',
    'dataChat.online': 'Online',
    'dataChat.offline': 'Offline',
    'dataChat.quickReplies': 'Quick Replies',
    'dataChat.typePlaceholder': 'Enter: Send message, Shift + Enter: New line',
    'dataChat.tags': 'Tags',
    'dataChat.addTags': 'Add tags',
    'dataChat.assign': 'Assign',
    'dataChat.notes': 'Notes',
    'dataChat.addNote': 'Add Note',
    'dataChat.keepRecords': 'Keep records in Notes',
    'dataChat.recordInfo': 'Record info on this user and your interactions with them, and leave handoff notes for your team.',
    'dataChat.followUp': 'Follow up',
    'dataChat.resolve': 'Resolve',
    'dataChat.downloadHistory': 'Download chat history',
    'dataChat.delete': 'Delete',
    'dataChat.conversations': 'conversations',
    'dataChat.live': 'Live',
    'dataChat.connecting': 'Connecting...',
    'dataChat.connected': 'Connected',
    'dataChat.disconnected': 'Disconnected',
    'dataChat.reconnecting': 'Reconnecting...',
    'dataChat.suspended': 'Suspended',
    'dataChat.selectConversation': 'Select a conversation',
    'dataChat.selectConversationDesc': 'Choose a conversation from the left to start chatting',
    'dataChat.noConversations': 'No conversations',
    'dataChat.selectChannel': 'Select a channel below',
    'dataChat.noSpamMessages': 'No spam messages',
    'dataChat.emoji': 'Emoji',
    'dataChat.sticker': 'Sticker',
    'dataChat.quick': 'Quick',
    'dataChat.searchTemplates': 'Search templates...',
    'dataChat.selectThenSend': 'Select message, then send',
    'dataChat.noSearchResults': 'No search results',
    'dataChat.casino': 'Casino',
    'dataChat.service': 'Service',
    'dataChat.apology': 'Apology',
    'dataChat.send': 'Send',
    'dataChat.mute': 'Mute',
    'dataChat.unmute': 'Unmute',
    'dataChat.pin': 'Pin',
    'dataChat.unpin': 'Unpin',
    'dataChat.archive': 'Archive',
    'dataChat.unarchive': 'Unarchive',
    'dataChat.customerInfo': 'Customer Info',
    'dataChat.channel': 'Channel',
    'dataChat.lastActive': 'Last Active',
    'dataChat.totalMessages': 'Total Messages',
    'dataChat.firstContact': 'First Contact',
    'dataChat.quickActions': 'Quick Actions',
    'dataChat.manualReconnect': 'Manual Reconnect',
    'dataChat.searchTitles': 'Search titles',
    'dataChat.sortBy': 'Sort by:',
    'dataChat.recentlyCreated': 'Recently created',
    'dataChat.titleAZ': 'Title A-Z',
    'dataChat.noQuickReplies': 'No quick replies yet',
    'dataChat.noQuickRepliesDesc': 'Create shortcuts for frequently used messages to reply faster',
    'dataChat.addQuickReply': 'Add Quick Reply',
    'dataChat.editQuickReply': 'Edit Quick Reply',
    'dataChat.titleLabel': 'Title',
    'dataChat.titlePlaceholder': 'Enter a memorable title...',
    'dataChat.titleHint': 'Title is for your reference only, users won\'t see it.',
    'dataChat.messageContent': 'Message Content',
    'dataChat.lineEmoji': 'LINE Emoji',
    'dataChat.searchInConversation': 'Search in this conversation...',
    'dataChat.searchMessages': 'Search messages...',
    'dataChat.inputPlaceholder': 'Enter: Send message, Shift + Enter: New line',
    'dataChat.newTag': 'New tag...',
    'dataChat.writeNote': 'Write a note...',
    'dataChat.noMessages': 'No messages yet',
    'dataChat.pinChat': 'Pin Chat',
    'dataChat.unpinChat': 'Unpin Chat',
    'dataChat.muteNotifications': 'Mute Notifications',
    'dataChat.unmuteNotifications': 'Unmute Notifications',
    'dataChat.archiveChat': 'Archive Chat',
    'dataChat.markSpam': 'Mark as Spam',
    'dataChat.notSpam': 'Not Spam',
    'dataChat.clearMessages': 'Clear Messages',
    'dataChat.confirmClearMessages': 'Delete all messages in this chat? (User can still send new messages)',
    'dataChat.clickEmojiToInsert': 'Click emoji to insert',
    'dataChat.selectToken': 'Select LINE Token',
    'dataChat.useInMessage': 'Use in message',
    'dataChat.noChannelSelected': 'Select a channel below',
    'dataChat.preview': 'Preview',
    'dataChat.previewMessage': 'Preview Message',
    'dataChat.selectMessagePreview': 'Select a message from the left to preview',
    'dataChat.selectFromLeft': 'Select from left',
    'dataChat.cancel': 'Cancel',
    'dataChat.use': 'Use',
    
    // Permissions
    'permissions.title': 'Permissions',
    'permissions.subtitle': 'Manage roles and access permissions',
    'permissions.addRole': 'Add New Role',
    'permissions.searchPlaceholder': 'Search roles...',
    'permissions.users': 'users',
    'permissions.viewUsers': 'View Users',
    'permissions.edit': 'Edit',
    'permissions.accessPermissions': 'Access Permissions',
    'permissions.usersInRole': 'Users in this role',
    'permissions.addUser': 'Add User',
    'permissions.deleteRole': 'Delete Role',
    'permissions.cancel': 'Cancel',
    'permissions.saveChanges': 'Save Changes',
    'permissions.manageUsers': 'Manage Users',
    'permissions.managePermissions': 'Manage Permissions',
    'permissions.viewReports': 'View Reports',
    'permissions.manageData': 'Manage Data',
    'permissions.replyChat': 'Reply Chat',
    'permissions.systemSettings': 'System Settings',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': "Welcome back! Here's what's happening today.",
    'dashboard.downloadReport': 'Download Report',
    'dashboard.last7days': 'Last 7 days',
    'dashboard.last30days': 'Last 30 days',
    'dashboard.last90days': 'Last 90 days',
    'dashboard.thisYear': 'This year',
    'dashboard.totalRevenue': 'Total Revenue',
    'dashboard.totalCustomers': 'Total Customers',
    'dashboard.totalOrders': 'Total Orders',
    'dashboard.conversionRate': 'Conversion Rate',
    'dashboard.vsLastPeriod': 'vs last period',
    'dashboard.loadingStats': 'Loading stats...',
    'dashboard.failedToLoad': 'Failed to load stats',
    // Financial Dashboard
    'dashboard.totalDeposits': 'Total Deposits',
    'dashboard.totalWithdrawals': 'Total Withdrawals',
    'dashboard.netProfit': 'Net Profit',
    'dashboard.totalBalance': 'Total Balance',
    'dashboard.currentBalance': 'Current Balance',
    'dashboard.transfers': 'Transfers',
    'dashboard.cashWithdrawals': 'Cash Withdrawals',
    'dashboard.expenses': 'Expenses',
    'dashboard.activeWebsites': 'Active Websites',
    'dashboard.activeBanks': 'Active Banks',
    'dashboard.transactions': 'Transactions',
    'dashboard.items': 'items',
    'dashboard.websites': 'Websites',
    'dashboard.bankAccounts': 'Bank Accounts',
    'dashboard.financialOverview': 'Financial Overview',
    'dashboard.last7DaysChart': 'Last 7 Days Financial Trend',
    'dashboard.deposits': 'Deposits',
    'dashboard.withdrawals': 'Withdrawals',
    'dashboard.profit': 'Profit',
    'dashboard.noDataAvailable': 'No data available',
    'dashboard.websitePerformance': 'Website Performance',
    'dashboard.topPerformingWebsites': 'Top Performing Websites',
    'dashboard.recentTransactions': 'Recent Transactions',
    'dashboard.latestTransactions': 'Latest Transactions',
    'dashboard.noTransactions': 'No transactions found',
    'dashboard.transfer': 'Transfer',
    'dashboard.withdrawal': 'Withdrawal',
    'dashboard.expense': 'Expense',
    'dashboard.type': 'Type',
    'dashboard.description': 'Description',
    'dashboard.website': 'Website',
    'dashboard.amount': 'Amount',
    'dashboard.status': 'Status',
    'dashboard.date': 'Date',
    'dashboard.completed': 'Completed',
    'dashboard.pending': 'Pending',
    'dashboard.paid': 'Paid',
    'dashboard.unpaid': 'Unpaid',
    'dashboard.failed': 'Failed',
    'dashboard.viewAll': 'View All',
    'dashboard.refresh': 'Refresh',
    'dashboard.export': 'Export',
    'dashboard.rank': 'Rank',
    'dashboard.noWebsites': 'No websites found',
    'dashboard.total': 'Total',
    'dashboard.quickStats': 'Quick Stats',
    'dashboard.lastMonth': 'Last 1 Month',
    'dashboard.last3Months': 'Last 3 Months',
    'dashboard.last6Months': 'Last 6 Months',
    
    // Revenue Chart
    'revenueChart.title': 'Revenue Trends',
    'revenueChart.subtitle': 'Monthly revenue and profit overview',
    'revenueChart.revenue': 'Revenue',
    'revenueChart.profit': 'Profit',
    'revenueChart.totalRevenue': 'Total Revenue',
    'revenueChart.totalProfit': 'Total Profit',
    'revenueChart.loading': 'Loading revenue data...',
    
    // Sales Chart
    'salesChart.title': 'Weekly Sales',
    'salesChart.subtitle': 'Daily sales performance',
    'salesChart.thisWeek': 'This Week',
    'salesChart.lastWeek': 'Last Week',
    'salesChart.sales': 'Sales',
    'salesChart.orders': 'Orders',
    'salesChart.loading': 'Loading sales data...',
    
    // Recent Orders
    'recentOrders.title': 'Recent Orders',
    'recentOrders.subtitle': 'Latest transactions',
    'recentOrders.viewAll': 'View All',
    'recentOrders.orderId': 'Order ID',
    'recentOrders.customer': 'Customer',
    'recentOrders.amount': 'Amount',
    'recentOrders.status': 'Status',
    'recentOrders.date': 'Date',
    'recentOrders.loading': 'Loading orders...',
    'recentOrders.completed': 'Completed',
    'recentOrders.processing': 'Processing',
    'recentOrders.pending': 'Pending',
    'recentOrders.cancelled': 'Cancelled',
    
    // Top Products
    'topProducts.title': 'Top Products',
    'topProducts.subtitle': 'Best selling items this month',
    'topProducts.viewAll': 'View All',
    'topProducts.sold': 'sold',
    'topProducts.loading': 'Loading products...',
    
    // Login Page
    'login.title': 'DATA CENTER',
    'login.subtitle': 'Management System',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing in...',
    'login.errorInvalidCredentials': 'Invalid email or password',
    'login.errorConnection': 'Connection error. Please try again.',
    
    // Common Form
    'form.add': 'Add',
    'form.edit': 'Edit',
    'form.delete': 'Delete',
    'form.save': 'Save',
    'form.cancel': 'Cancel',
    'form.close': 'Close',
    'form.confirm': 'Confirm',
    'form.search': 'Search',
    'form.loading': 'Loading...',
    'form.noData': 'No data found',
    'form.required': 'This field is required',
    'form.success': 'Success',
    'form.error': 'Error',
    'form.warning': 'Warning',
    'form.info': 'Info',
    'form.yes': 'Yes',
    'form.no': 'No',
    'form.selectOption': 'Select option',
    'form.addNew': 'Add New',
    'form.editItem': 'Edit Item',
    'form.deleteConfirm': 'Are you sure you want to delete this item?',
    'form.deleteSuccess': 'Deleted successfully',
    'form.saveSuccess': 'Saved successfully',
    'form.updateSuccess': 'Updated successfully',
    'form.createSuccess': 'Created successfully',
    'form.failedToLoad': 'Failed to load data',
    'form.failedToSave': 'Failed to save data',
    'form.failedToDelete': 'Failed to delete',
    
    // Salaries Page
    'salaries.title': 'Employee Salaries',
    'salaries.subtitle': 'Salary Management',
    'salaries.addNew': 'Add Salary',
    'salaries.employee': 'Employee',
    'salaries.month': 'Month',
    'salaries.website': 'Website',
    'salaries.position': 'Position',
    'salaries.baseSalary': 'Base Salary',
    'salaries.positionAllowance': 'Position Allowance',
    'salaries.commission': 'Commission',
    'salaries.diligenceAllowance': 'Diligence Allowance',
    'salaries.shiftAllowance': 'Shift Allowance',
    'salaries.overtime': 'Overtime',
    'salaries.bonus': 'Bonus',
    'salaries.totalSalary': 'Total Salary',
    'salaries.status': 'Status',
    'salaries.paid': 'Paid',
    'salaries.unpaid': 'Unpaid',
    'salaries.payAll': 'Pay All',
    'salaries.generateSlip': 'Generate Slip',
    'salaries.printSlip': 'Print Slip',
    'salaries.downloadSlip': 'Download Slip',
    'salaries.totalEmployees': 'Total Employees',
    'salaries.totalPaid': 'Total Paid',
    'salaries.totalUnpaid': 'Total Unpaid',
    'salaries.totalAmount': 'Total Amount',
    'salaries.selectEmployee': 'Select Employee',
    'salaries.selectWebsite': 'Select Website',
    'salaries.allWebsites': 'All Websites',
    'salaries.allStatus': 'All Status',
    'salaries.searchPlaceholder': 'Search employee...',
    'salaries.paySlip': 'Pay Slip',
    'salaries.paySlipMonth': 'Pay Slip for',
    'salaries.bankAccount': 'Bank Account',
    'salaries.netPay': 'Net Pay',
    'salaries.income': 'Income',
    'salaries.deductions': 'Deductions',
    'salaries.employeeInfo': 'Employee Information',
    'salaries.nickname': 'Nickname',
    
    // No Access Page
    'noAccess.redirecting': 'Redirecting...',
    
    // Users Page
    'users.title': 'Manage Users',
    'users.subtitle': 'User Management',
    'users.addNew': 'Add User',
    'users.editUser': 'Edit User',
    'users.name': 'Name',
    'users.user': 'User',
    'users.email': 'Email',
    'users.role': 'Role',
    'users.employee': 'Employee',
    'users.createdAt': 'Created At',
    'users.status': 'Status',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.searchPlaceholder': 'Search users...',
    'users.password': 'Password',
    'users.confirmPassword': 'Confirm Password',
    'users.selectRole': 'Select Role',
    'users.leaveBlankPassword': 'Leave blank to keep current password',
    'users.enterUserInfo': 'Enter user information',
    'users.admin': 'Admin',
    'users.notLinked': 'Not linked',
  },
  th: {
    // Common
    'common.search': 'ค้นหา...',
    'common.logout': 'ออกจากระบบ',
    'common.filter': 'กรอง',
    'common.export': 'Export Report',
    'common.all': 'ทั้งหมด',
    'common.status': 'สถานะ',
    'common.date': 'วันที่',
    'common.time': 'วันที่/เวลา',
    'common.amount': 'จำนวนเงิน',
    'common.actions': 'Actions',
    'common.showing': 'แสดง',
    'common.of': 'จาก',
    'common.items': 'รายการ',
    'common.total': 'รวมทั้งหมด',
    'common.note': 'หมายเหตุ',
    'common.approvedBy': 'อนุมัติโดย',
    'common.bank': 'ธนาคาร',
    'common.account': 'เลขบัญชี',
    'common.from': 'จาก',
    'common.to': 'ถึง',
    
    // Status
    'status.completed': 'สำเร็จ',
    'status.pending': 'รอดำเนินการ',
    'status.failed': 'ไม่สำเร็จ',
    'status.all': 'ทุกสถานะ',
    
    // Sidebar
    'sidebar.dashboard': 'แดชบอร์ด',
    'sidebar.analytics': 'วิเคราะห์',
    'sidebar.dataManagement': 'จัดการข้อมูล',
    'sidebar.manageWebsites': 'จัดการเว็บไซต์',
    'sidebar.manageBanks': 'จัดการธนาคาร',
    'sidebar.manageEmployees': 'จัดการพนักงาน',
    'sidebar.manageSalaryBase': 'จัดการฐานเงินเดือน',
    'sidebar.manageLineTokens': 'จัดการโทเค้นไลน์',
    'sidebar.reports': 'รายงาน',
    'sidebar.products': 'สินค้า',
    'sidebar.permissions': 'จัดการสิทธิ์',
    'sidebar.dataChat': 'แชทข้อมูล',
    'sidebar.manageUsers': 'จัดการผู้ใช้',
    'sidebar.settings': 'ตั้งค่า',
    'sidebar.help': 'ช่วยเหลือ',
    'sidebar.dailySummary': 'สรุปรายวัน',
    'sidebar.cashWithdrawal': 'ถอนเงินสด',
    'sidebar.transfer': 'โยกเงิน',
    'sidebar.dailyBalance': 'ยอดเงินคงเหลือรายวัน',
    'sidebar.expenses': 'ค่าใช้จ่าย',
    'sidebar.salaries': 'เงินเดือนพนักงาน',
    
    // Data Management - Websites
    'websites.title': 'จัดการเว็บไซต์',
    'websites.subtitle': 'จัดการข้อมูลเว็บไซต์',
    'websites.addNew': 'เพิ่มเว็บไซต์',
    'websites.id': 'รหัส',
    'websites.name': 'ชื่อเว็บไซต์',
    'websites.url': 'URL',
    'websites.status': 'สถานะ',
    'websites.active': 'ใช้งาน',
    'websites.inactive': 'ไม่ใช้งาน',
    'websites.searchPlaceholder': 'ค้นหาเว็บไซต์...',
    
    // Data Management - Banks
    'banks.title': 'จัดการธนาคาร',
    'banks.subtitle': 'จัดการบัญชีธนาคาร',
    'banks.addNew': 'เพิ่มบัญชี',
    'banks.id': 'รหัส',
    'banks.type': 'ประเภท',
    'banks.bank': 'ธนาคาร',
    'banks.deposit': 'ฝาก',
    'banks.withdrawal': 'ถอน',
    'banks.payment': 'ชำระเงิน',
    'banks.hold': 'พักเงิน',
    'banks.accountName': 'ชื่อบัญชี',
    'banks.accountNumber': 'เลขบัญชี',
    'banks.status': 'สถานะ',
    'banks.active': 'ใช้งาน',
    'banks.inactive': 'ไม่ใช้งาน',
    'banks.searchPlaceholder': 'ค้นหาธนาคาร...',
    'banks.allTypes': 'ทุกประเภท',
    'banks.allStatus': 'ทุกสถานะ',
    
    // Data Management - Employees
    'employees.title': 'จัดการพนักงาน',
    'employees.subtitle': 'จัดการข้อมูลพนักงาน',
    'employees.addNew': 'เพิ่มพนักงาน',
    'employees.id': 'รหัส',
    'employees.website': 'เว็บไซต์',
    'employees.websites': 'เว็บไซต์',
    'employees.fullName': 'ชื่อ-สกุล',
    'employees.position': 'ตำแหน่ง',
    'employees.receivingAccount': 'บัญชีรับเงิน',
    'employees.accountName': 'ชื่อบัญชี',
    'employees.accountNumber': 'เลขบัญชี',
    'employees.bank': 'ธนาคาร',
    'employees.status': 'สถานะ',
    'employees.active': 'ใช้งาน',
    'employees.inactive': 'ไม่ใช้งาน',
    'employees.searchPlaceholder': 'ค้นหาพนักงาน...',
    'employees.allWebsites': 'ทุกเว็บไซต์',
    'employees.allStatus': 'ทุกสถานะ',
    'employees.total': 'ทั้งหมด',
    'employees.notLinked': 'ยังไม่เชื่อมโยง',
    
    // Data Management - Salary Base
    'salaryBase.title': 'จัดการฐานเงินเดือน',
    'salaryBase.subtitle': 'จัดการตำแหน่งและฐานเงินเดือน',
    'salaryBase.addNew': 'เพิ่มตำแหน่ง',
    'salaryBase.position': 'ตำแหน่ง',
    'salaryBase.baseSalary': 'ฐานเงินเดือน',
    'salaryBase.positionAllowance': 'ค่าตำแหน่ง',
    'salaryBase.totalCompensation': 'รวมค่าตอบแทน',
    'salaryBase.searchPlaceholder': 'ค้นหาตำแหน่ง...',
    'salaryBase.totalPositions': 'ตำแหน่งทั้งหมด',
    'salaryBase.avgSalary': 'เงินเดือนเฉลี่ย',
    'salaryBase.maxSalary': 'เงินเดือนสูงสุด',
    
    // Data Management - LINE Tokens
    'lineTokens.title': 'จัดการโทเค้นไลน์',
    'lineTokens.subtitle': 'จัดการโทเค้น LINE OA',
    'lineTokens.addNew': 'เพิ่มโทเค้น',
    'lineTokens.totalTokens': 'โทเค้นทั้งหมด',
    'lineTokens.active': 'ใช้งาน',
    'lineTokens.inactive': 'ไม่ใช้งาน',
    'lineTokens.expired': 'หมดอายุ',
    'lineTokens.tokenName': 'ชื่อโทเค้น',
    'lineTokens.channelId': 'Channel ID',
    'lineTokens.token': 'Access Token',
    'lineTokens.website': 'เว็บไซต์',
    'lineTokens.lastUsed': 'ใช้ล่าสุด',
    'lineTokens.searchPlaceholder': 'ค้นหาโทเค้น...',
    
    // Daily Summary
    'dailySummary.title': 'สรุปรายวัน',
    'dailySummary.subtitle': 'รายงานสรุปรายวัน',
    'dailySummary.totalRevenue': 'ยอดรายได้รวม',
    'dailySummary.orders': 'จำนวนออเดอร์',
    'dailySummary.customers': 'จำนวนลูกค้า',
    'dailySummary.avgOrder': 'ค่าเฉลี่ยต่อออเดอร์',
    'dailySummary.hourlyRevenue': 'ยอดรายได้รายชั่วโมง',
    'dailySummary.topProducts': 'สินค้าขายดี',
    'dailySummary.product': 'สินค้า',
    'dailySummary.sales': 'ขายได้',
    'dailySummary.revenue': 'รายได้',
    'dailySummary.vsYesterday': 'เทียบกับเมื่อวาน',
    
    // Cash Withdrawal
    'cashWithdrawal.title': 'ถอนเงินสด',
    'cashWithdrawal.subtitle': 'รายงานการถอนเงินสด',
    'cashWithdrawal.totalWithdrawals': 'ยอดถอนทั้งหมด',
    'cashWithdrawal.completed': 'สำเร็จ',
    'cashWithdrawal.pending': 'รอดำเนินการ',
    'cashWithdrawal.failed': 'ไม่สำเร็จ',
    'cashWithdrawal.transactionId': 'เลขที่รายการ',
    'cashWithdrawal.searchPlaceholder': 'ค้นหาเลขที่รายการ, ธนาคาร...',
    
    // Transfer
    'transfer.title': 'โยกเงิน',
    'transfer.subtitle': 'รายงานการโยกเงิน',
    'transfer.totalTransfers': 'ยอดโอนทั้งหมด',
    'transfer.transactionCount': 'จำนวนรายการ',
    'transfer.pending': 'รอดำเนินการ',
    'transfer.todayTransfers': 'ยอดโอนวันนี้',
    'transfer.transactionId': 'เลขที่รายการ',
    'transfer.fromAccount': 'จากบัญชี',
    'transfer.toAccount': 'ไปยังบัญชี',
    'transfer.searchPlaceholder': 'ค้นหาเลขที่รายการ, หมายเหตุ...',
    
    // Daily Balance
    'dailyBalance.title': 'ยอดเงินคงเหลือรายวัน',
    'dailyBalance.subtitle': 'รายงานยอดเงินคงเหลือรายวัน',
    'dailyBalance.totalBalance': 'ยอดคงเหลือรวม',
    'dailyBalance.todayDeposits': 'ยอดฝากวันนี้',
    'dailyBalance.todayWithdrawals': 'ยอดถอนวันนี้',
    'dailyBalance.netChange': 'เปลี่ยนแปลงสุทธิ',
    'dailyBalance.currentBalance': 'ยอดคงเหลือปัจจุบัน',
    'dailyBalance.openingBalance': 'ยอดยกมา',
    'dailyBalance.deposits': 'ยอดฝาก',
    'dailyBalance.withdrawals': 'ยอดถอน',
    'dailyBalance.transfers': 'โยกเงิน',
    'dailyBalance.closingBalance': 'ยอดคงเหลือ',
    'dailyBalance.allBanks': 'ทุกธนาคาร',
    'dailyBalance.noteTitle': 'หมายเหตุ',
    'dailyBalance.noteText': 'ยอดคงเหลือจะถูกอัพเดทอัตโนมัติทุก 15 นาที ข้อมูลอาจมีความคลาดเคลื่อนเล็กน้อย กรุณาตรวจสอบยอดจริงจากระบบธนาคารอีกครั้ง',
    
    // Expenses
    'expenses.title': 'ค่าใช้จ่าย',
    'expenses.subtitle': 'รายงานค่าใช้จ่าย',
    'expenses.totalExpenses': 'ค่าใช้จ่ายทั้งหมด',
    'expenses.pending': 'รออนุมัติ',
    'expenses.approved': 'อนุมัติแล้ว',
    'expenses.rejected': 'ไม่อนุมัติ',
    'expenses.category': 'หมวดหมู่',
    'expenses.description': 'รายละเอียด',
    'expenses.requestedBy': 'ผู้ขอเบิก',
    'expenses.searchPlaceholder': 'ค้นหาค่าใช้จ่าย...',
    'expenses.office': 'อุปกรณ์สำนักงาน',
    'expenses.travel': 'ค่าเดินทาง',
    'expenses.utilities': 'ค่าสาธารณูปโภค',
    'expenses.marketing': 'ค่าการตลาด',
    'expenses.equipment': 'อุปกรณ์',
    'expenses.other': 'อื่นๆ',
    
    // Payroll
    'payroll.title': 'เงินเดือนพนักงาน',
    'payroll.subtitle': 'รายงานเงินเดือนพนักงาน',
    'payroll.totalPayroll': 'ยอดเงินเดือนทั้งหมด',
    'payroll.totalEmployees': 'จำนวนพนักงาน',
    'payroll.paid': 'จ่ายแล้ว',
    'payroll.pending': 'รอจ่าย',
    'payroll.employeeId': 'รหัสพนักงาน',
    'payroll.employeeName': 'ชื่อพนักงาน',
    'payroll.department': 'แผนก',
    'payroll.position': 'ตำแหน่ง',
    'payroll.baseSalary': 'เงินเดือนพื้นฐาน',
    'payroll.bonus': 'โบนัส',
    'payroll.deductions': 'หักเงิน',
    'payroll.netSalary': 'เงินสุทธิ',
    'payroll.paymentDate': 'วันที่จ่าย',
    'payroll.searchPlaceholder': 'ค้นหาพนักงาน...',
    'payroll.allDepartments': 'ทุกแผนก',
    'payroll.accounting': 'บัญชี',
    'payroll.sales': 'ฝ่ายขาย',
    'payroll.it': 'ไอที',
    'payroll.hr': 'ทรัพยากรบุคคล',
    'payroll.operations': 'ปฏิบัติการ',
    
    // Data Chat
    'dataChat.title': 'แชทลูกค้า',
    'dataChat.subtitle': 'จัดการแชทลูกค้า',
    'dataChat.searchPlaceholder': 'ค้นหา...',
    'dataChat.all': 'ทั้งหมด',
    'dataChat.unread': 'ยังไม่อ่าน',
    'dataChat.pinned': 'ปักหมุด',
    'dataChat.archived': 'เก็บถาวร',
    'dataChat.spam': 'สแปม',
    'dataChat.online': 'ออนไลน์',
    'dataChat.offline': 'ออฟไลน์',
    'dataChat.quickReplies': 'ข้อความด่วน',
    'dataChat.typePlaceholder': 'Enter: ส่งข้อความ, Shift + Enter: ขึ้นบรรทัดใหม่',
    'dataChat.tags': 'แท็ก',
    'dataChat.addTags': 'เพิ่มแท็ก',
    'dataChat.assign': 'มอบหมาย',
    'dataChat.notes': 'บันทึก',
    'dataChat.addNote': 'เพิ่มบันทึก',
    'dataChat.keepRecords': 'เก็บบันทึกไว้ใน Notes',
    'dataChat.recordInfo': 'บันทึกข้อมูลผู้ใช้และการสนทนา รวมถึงบันทึกส่งต่อให้ทีมของคุณ',
    'dataChat.followUp': 'ติดตาม',
    'dataChat.resolve': 'แก้ไขแล้ว',
    'dataChat.downloadHistory': 'ดาวน์โหลดประวัติแชท',
    'dataChat.delete': 'ลบ',
    'dataChat.conversations': 'การสนทนา',
    'dataChat.live': 'ถ่ายทอดสด',
    'dataChat.connecting': 'กำลังเชื่อมต่อ...',
    'dataChat.connected': 'เชื่อมต่อแล้ว',
    'dataChat.disconnected': 'ขาดการเชื่อมต่อ',
    'dataChat.reconnecting': 'กำลังเชื่อมต่อใหม่...',
    'dataChat.suspended': 'ถูกระงับ',
    'dataChat.selectConversation': 'เลือกการสนทนา',
    'dataChat.selectConversationDesc': 'เลือกการสนทนาจากรายการด้านซ้ายเพื่อเริ่มแชท',
    'dataChat.noConversations': 'ไม่มีการสนทนา',
    'dataChat.selectChannel': 'เลือกช่องทางด้านล่าง',
    'dataChat.noSpamMessages': 'ไม่มีข้อความสแปม',
    'dataChat.emoji': 'อีโมจิ',
    'dataChat.sticker': 'สติกเกอร์',
    'dataChat.quick': 'ด่วน',
    'dataChat.searchTemplates': 'ค้นหาข้อความ...',
    'dataChat.selectThenSend': 'เลือกข้อความ แล้วกดส่งเอง',
    'dataChat.noSearchResults': 'ไม่พบข้อความที่ค้นหา',
    'dataChat.casino': 'คาสิโน',
    'dataChat.service': 'บริการ',
    'dataChat.apology': 'ขออภัย',
    'dataChat.send': 'ส่ง',
    'dataChat.mute': 'ปิดเสียง',
    'dataChat.unmute': 'เปิดเสียง',
    'dataChat.pin': 'ปักหมุด',
    'dataChat.unpin': 'เลิกปักหมุด',
    'dataChat.archive': 'เก็บถาวร',
    'dataChat.unarchive': 'ยกเลิกเก็บถาวร',
    'dataChat.customerInfo': 'ข้อมูลลูกค้า',
    'dataChat.channel': 'ช่องทาง',
    'dataChat.lastActive': 'ใช้งานล่าสุด',
    'dataChat.totalMessages': 'ข้อความทั้งหมด',
    'dataChat.firstContact': 'ติดต่อครั้งแรก',
    'dataChat.quickActions': 'การกระทำด่วน',
    'dataChat.manualReconnect': 'เชื่อมต่อใหม่',
    'dataChat.searchTitles': 'ค้นหาหัวข้อ',
    'dataChat.sortBy': 'เรียงตาม:',
    'dataChat.recentlyCreated': 'สร้างล่าสุด',
    'dataChat.titleAZ': 'ชื่อ ก-ฮ',
    'dataChat.noQuickReplies': 'ยังไม่มีข้อความด่วน',
    'dataChat.noQuickRepliesDesc': 'สร้างช็อตคัทสำหรับข้อความที่ใช้บ่อยเพื่อตอบกลับเร็วขึ้น',
    'dataChat.addQuickReply': 'เพิ่มข้อความด่วน',
    'dataChat.editQuickReply': 'แก้ไขข้อความด่วน',
    'dataChat.titleLabel': 'หัวข้อ',
    'dataChat.titlePlaceholder': 'ใส่หัวข้อที่จำง่าย...',
    'dataChat.titleHint': 'หัวข้อใช้สำหรับอ้างอิงเท่านั้น ลูกค้าจะไม่เห็น',
    'dataChat.messageContent': 'ข้อความ',
    'dataChat.lineEmoji': 'LINE Emoji',
    'dataChat.clickEmojiToInsert': 'คลิกอีโมจิเพื่อแทรก',
    'dataChat.selectToken': 'เลือก LINE Token',
    'dataChat.useInMessage': 'ใช้ในข้อความ',
    'dataChat.noChannelSelected': 'เลือกช่องทางด้านล่าง',
    'dataChat.preview': 'ตัวอย่าง',
    'dataChat.previewMessage': 'ตัวอย่างข้อความ',
    'dataChat.selectMessagePreview': 'เลือกข้อความจากรายการทางซ้ายเพื่อดูตัวอย่าง',
    'dataChat.selectFromLeft': 'เลือกข้อทางด้านซ้าย',
    'dataChat.cancel': 'ยกเลิก',
    'dataChat.use': 'ใช้งาน',
    'dataChat.searchInConversation': 'ค้นหาในการสนทนานี้...',
    'dataChat.searchMessages': 'ค้นหาข้อความ...',
    'dataChat.inputPlaceholder': 'Enter: ส่งข้อความ, Shift + Enter: ขึ้นบรรทัดใหม่',
    'dataChat.newTag': 'แท็กใหม่...',
    'dataChat.writeNote': 'เขียนบันทึก...',
    'dataChat.noMessages': 'ยังไม่มีข้อความ',
    'dataChat.pinChat': 'ปักหมุดแชท',
    'dataChat.unpinChat': 'เลิกปักหมุดแชท',
    'dataChat.muteNotifications': 'ปิดการแจ้งเตือน',
    'dataChat.unmuteNotifications': 'เปิดการแจ้งเตือน',
    'dataChat.archiveChat': 'เก็บถาวรแชท',
    'dataChat.markSpam': 'ทำเครื่องหมายสแปม',
    'dataChat.notSpam': 'ไม่ใช่สแปม',
    'dataChat.clearMessages': 'ล้างข้อความ',
    'dataChat.confirmClearMessages': 'ต้องการลบข้อความทั้งหมดในแชทนี้หรือไม่? (user จะยังสามารถส่งข้อความมาได้อีก)',
    
    // Permissions
    'permissions.title': 'จัดการสิทธิ์',
    'permissions.subtitle': 'กำหนดบทบาทและสิทธิ์การเข้าถึง',
    'permissions.addRole': 'เพิ่มบทบาทใหม่',
    'permissions.searchPlaceholder': 'ค้นหาบทบาท...',
    'permissions.users': 'ผู้ใช้',
    'permissions.viewUsers': 'ดูผู้ใช้',
    'permissions.edit': 'แก้ไข',
    'permissions.accessPermissions': 'สิทธิ์การเข้าถึง',
    'permissions.usersInRole': 'ผู้ใช้ในบทบาทนี้',
    'permissions.addUser': 'เพิ่มผู้ใช้',
    'permissions.deleteRole': 'ลบบทบาท',
    'permissions.cancel': 'ยกเลิก',
    'permissions.saveChanges': 'บันทึกการเปลี่ยนแปลง',
    'permissions.manageUsers': 'จัดการผู้ใช้',
    'permissions.managePermissions': 'จัดการสิทธิ์',
    'permissions.viewReports': 'ดูรายงาน',
    'permissions.manageData': 'จัดการข้อมูล',
    'permissions.replyChat': 'ตอบแชท',
    'permissions.systemSettings': 'ตั้งค่าระบบ',
    
    // Dashboard
    'dashboard.title': 'แดชบอร์ด',
    'dashboard.welcome': 'ยินดีต้อนรับ! นี่คือสิ่งที่เกิดขึ้นวันนี้',
    'dashboard.downloadReport': 'ดาวน์โหลดรายงาน',
    'dashboard.last7days': '7 วันที่ผ่านมา',
    'dashboard.last30days': '30 วันที่ผ่านมา',
    'dashboard.last90days': '90 วันที่ผ่านมา',
    'dashboard.thisYear': 'ปีนี้',
    'dashboard.totalRevenue': 'รายได้ทั้งหมด',
    'dashboard.totalCustomers': 'ลูกค้าทั้งหมด',
    'dashboard.totalOrders': 'ออเดอร์ทั้งหมด',
    'dashboard.conversionRate': 'อัตราการแปลง',
    'dashboard.vsLastPeriod': 'เทียบกับช่วงก่อน',
    'dashboard.loadingStats': 'กำลังโหลดข้อมูล...',
    'dashboard.failedToLoad': 'โหลดข้อมูลไม่สำเร็จ',
    // Financial Dashboard
    'dashboard.totalDeposits': 'ยอดฝากทั้งหมด',
    'dashboard.totalWithdrawals': 'ยอดถอนทั้งหมด',
    'dashboard.netProfit': 'กำไรสุทธิ',
    'dashboard.totalBalance': 'ยอดคงเหลือทั้งหมด',
    'dashboard.currentBalance': 'ยอดคงเหลือปัจจุบัน',
    'dashboard.transfers': 'โอนเงิน',
    'dashboard.cashWithdrawals': 'เบิกเงินสด',
    'dashboard.expenses': 'ค่าใช้จ่าย',
    'dashboard.activeWebsites': 'เว็บไซต์ที่ใช้งาน',
    'dashboard.activeBanks': 'ธนาคารที่ใช้งาน',
    'dashboard.transactions': 'ธุรกรรม',
    'dashboard.items': 'รายการ',
    'dashboard.websites': 'เว็บไซต์',
    'dashboard.bankAccounts': 'บัญชีธนาคาร',
    'dashboard.financialOverview': 'ภาพรวมการเงิน',
    'dashboard.last7DaysChart': 'แนวโน้มการเงิน 7 วันที่ผ่านมา',
    'dashboard.deposits': 'ยอดฝาก',
    'dashboard.withdrawals': 'ยอดถอน',
    'dashboard.profit': 'กำไร',
    'dashboard.noDataAvailable': 'ไม่มีข้อมูล',
    'dashboard.websitePerformance': 'ประสิทธิภาพเว็บไซต์',
    'dashboard.topPerformingWebsites': 'เว็บไซต์ที่มีผลงานดีที่สุด',
    'dashboard.recentTransactions': 'ธุรกรรมล่าสุด',
    'dashboard.latestTransactions': 'รายการล่าสุด',
    'dashboard.noTransactions': 'ไม่พบธุรกรรม',
    'dashboard.transfer': 'โอนเงิน',
    'dashboard.withdrawal': 'ถอนเงิน',
    'dashboard.expense': 'ค่าใช้จ่าย',
    'dashboard.type': 'ประเภท',
    'dashboard.description': 'รายละเอียด',
    'dashboard.website': 'เว็บไซต์',
    'dashboard.amount': 'จำนวนเงิน',
    'dashboard.status': 'สถานะ',
    'dashboard.date': 'วันที่',
    'dashboard.completed': 'สำเร็จ',
    'dashboard.pending': 'รอดำเนินการ',
    'dashboard.paid': 'ชำระแล้ว',
    'dashboard.unpaid': 'ยังไม่ชำระ',
    'dashboard.failed': 'ล้มเหลว',
    'dashboard.viewAll': 'ดูทั้งหมด',
    'dashboard.refresh': 'รีเฟรช',
    'dashboard.export': 'ส่งออก',
    'dashboard.rank': 'อันดับ',
    'dashboard.noWebsites': 'ไม่พบเว็บไซต์',
    'dashboard.total': 'รวม',
    'dashboard.quickStats': 'สถิติด่วน',
    'dashboard.lastMonth': '1 เดือนที่ผ่านมา',
    'dashboard.last3Months': '3 เดือนที่ผ่านมา',
    'dashboard.last6Months': '6 เดือนที่ผ่านมา',
    
    // Revenue Chart
    'revenueChart.title': 'แนวโน้มรายได้',
    'revenueChart.subtitle': 'ภาพรวมรายได้และกำไรรายเดือน',
    'revenueChart.revenue': 'รายได้',
    'revenueChart.profit': 'กำไร',
    'revenueChart.totalRevenue': 'รายได้รวม',
    'revenueChart.totalProfit': 'กำไรรวม',
    'revenueChart.loading': 'กำลังโหลดข้อมูลรายได้...',
    
    // Sales Chart
    'salesChart.title': 'ยอดขายรายสัปดาห์',
    'salesChart.subtitle': 'ประสิทธิภาพการขายรายวัน',
    'salesChart.thisWeek': 'สัปดาห์นี้',
    'salesChart.lastWeek': 'สัปดาห์ก่อน',
    'salesChart.sales': 'ยอดขาย',
    'salesChart.orders': 'ออเดอร์',
    'salesChart.loading': 'กำลังโหลดข้อมูลยอดขาย...',
    
    // Recent Orders
    'recentOrders.title': 'ออเดอร์ล่าสุด',
    'recentOrders.subtitle': 'รายการล่าสุด',
    'recentOrders.viewAll': 'ดูทั้งหมด',
    'recentOrders.orderId': 'รหัสออเดอร์',
    'recentOrders.customer': 'ลูกค้า',
    'recentOrders.amount': 'จำนวนเงิน',
    'recentOrders.status': 'สถานะ',
    'recentOrders.date': 'วันที่',
    'recentOrders.loading': 'กำลังโหลดออเดอร์...',
    'recentOrders.completed': 'สำเร็จ',
    'recentOrders.processing': 'กำลังดำเนินการ',
    'recentOrders.pending': 'รอดำเนินการ',
    'recentOrders.cancelled': 'ยกเลิก',
    
    // Top Products
    'topProducts.title': 'สินค้าขายดี',
    'topProducts.subtitle': 'สินค้าขายดีประจำเดือนนี้',
    'topProducts.viewAll': 'ดูทั้งหมด',
    'topProducts.sold': 'ขายแล้ว',
    'topProducts.loading': 'กำลังโหลดสินค้า...',
    
    // Login Page
    'login.title': 'DATA CENTER',
    'login.subtitle': 'ระบบจัดการข้อมูล',
    'login.email': 'อีเมล',
    'login.password': 'รหัสผ่าน',
    'login.rememberMe': 'จดจำฉัน',
    'login.forgotPassword': 'ลืมรหัสผ่าน?',
    'login.signIn': 'เข้าสู่ระบบ',
    'login.signingIn': 'กำลังเข้าสู่ระบบ...',
    'login.errorInvalidCredentials': 'อีเมลหรือรหัสผ่านไม่ถูกต้อง',
    'login.errorConnection': 'เกิดข้อผิดพลาดในการเชื่อมต่อ กรุณาลองใหม่',
    
    // Common Form
    'form.add': 'เพิ่ม',
    'form.edit': 'แก้ไข',
    'form.delete': 'ลบ',
    'form.save': 'บันทึก',
    'form.cancel': 'ยกเลิก',
    'form.close': 'ปิด',
    'form.confirm': 'ยืนยัน',
    'form.search': 'ค้นหา',
    'form.loading': 'กำลังโหลด...',
    'form.noData': 'ไม่พบข้อมูล',
    'form.required': 'จำเป็นต้องกรอก',
    'form.success': 'สำเร็จ',
    'form.error': 'ข้อผิดพลาด',
    'form.warning': 'คำเตือน',
    'form.info': 'ข้อมูล',
    'form.yes': 'ใช่',
    'form.no': 'ไม่',
    'form.selectOption': 'เลือกตัวเลือก',
    'form.addNew': 'เพิ่มใหม่',
    'form.editItem': 'แก้ไขรายการ',
    'form.deleteConfirm': 'คุณแน่ใจหรือไม่ว่าต้องการลบรายการนี้?',
    'form.deleteSuccess': 'ลบสำเร็จ',
    'form.saveSuccess': 'บันทึกสำเร็จ',
    'form.updateSuccess': 'อัพเดทสำเร็จ',
    'form.createSuccess': 'สร้างสำเร็จ',
    'form.failedToLoad': 'โหลดข้อมูลไม่สำเร็จ',
    'form.failedToSave': 'บันทึกข้อมูลไม่สำเร็จ',
    'form.failedToDelete': 'ลบไม่สำเร็จ',
    
    // Salaries Page
    'salaries.title': 'เงินเดือนพนักงาน',
    'salaries.subtitle': 'จัดการเงินเดือน',
    'salaries.addNew': 'เพิ่มเงินเดือน',
    'salaries.employee': 'พนักงาน',
    'salaries.month': 'เดือน',
    'salaries.website': 'เว็บไซต์',
    'salaries.position': 'ตำแหน่ง',
    'salaries.baseSalary': 'เงินเดือนพื้นฐาน',
    'salaries.positionAllowance': 'ค่าตำแหน่ง',
    'salaries.commission': 'ค่าคอมมิชชั่น',
    'salaries.diligenceAllowance': 'ค่าขยัน',
    'salaries.shiftAllowance': 'ค่ากะ',
    'salaries.overtime': 'ค่าล่วงเวลา',
    'salaries.bonus': 'โบนัส',
    'salaries.totalSalary': 'เงินเดือนรวม',
    'salaries.status': 'สถานะ',
    'salaries.paid': 'จ่ายแล้ว',
    'salaries.unpaid': 'ยังไม่จ่าย',
    'salaries.payAll': 'จ่ายทั้งหมด',
    'salaries.generateSlip': 'สร้างสลิป',
    'salaries.printSlip': 'พิมพ์สลิป',
    'salaries.downloadSlip': 'ดาวน์โหลดสลิป',
    'salaries.totalEmployees': 'พนักงานทั้งหมด',
    'salaries.totalPaid': 'จ่ายแล้ว',
    'salaries.totalUnpaid': 'ยังไม่จ่าย',
    'salaries.totalAmount': 'ยอดรวม',
    'salaries.selectEmployee': 'เลือกพนักงาน',
    'salaries.selectWebsite': 'เลือกเว็บไซต์',
    'salaries.allWebsites': 'ทุกเว็บไซต์',
    'salaries.allStatus': 'ทุกสถานะ',
    'salaries.searchPlaceholder': 'ค้นหาพนักงาน...',
    'salaries.paySlip': 'ใบจ่ายเงินเดือน',
    'salaries.paySlipMonth': 'ใบจ่ายเงินเดือนประจำเดือน',
    'salaries.bankAccount': 'บัญชีธนาคาร',
    'salaries.netPay': 'รับสุทธิ',
    'salaries.income': 'รายได้',
    'salaries.deductions': 'หักเงิน',
    'salaries.employeeInfo': 'ข้อมูลพนักงาน',
    'salaries.nickname': 'ชื่อเล่น',
    
    // No Access Page
    'noAccess.redirecting': 'กำลังเปลี่ยนหน้า...',
    
    // Users Page
    'users.title': 'จัดการผู้ใช้',
    'users.subtitle': 'จัดการข้อมูลผู้ใช้',
    'users.addNew': 'เพิ่มผู้ใช้',
    'users.editUser': 'แก้ไขผู้ใช้',
    'users.name': 'ชื่อ',
    'users.user': 'ผู้ใช้',
    'users.email': 'อีเมล',
    'users.role': 'บทบาท',
    'users.employee': 'พนักงาน',
    'users.createdAt': 'วันที่สร้าง',
    'users.status': 'สถานะ',
    'users.active': 'ใช้งาน',
    'users.inactive': 'ไม่ใช้งาน',
    'users.searchPlaceholder': 'ค้นหาผู้ใช้...',
    'users.password': 'รหัสผ่าน',
    'users.confirmPassword': 'ยืนยันรหัสผ่าน',
    'users.selectRole': 'เลือกบทบาท',
    'users.leaveBlankPassword': 'เว้นว่างหากไม่ต้องการเปลี่ยน',
    'users.enterUserInfo': 'กรอกข้อมูลผู้ใช้',
    'users.admin': 'แอดมิน',
    'users.notLinked': 'ยังไม่เชื่อมโยง',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved && (saved === 'en' || saved === 'th')) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
