-- SQL สำหรับสร้างตารางทั้งหมดใน dev.db ตาม schema.prisma

CREATE TABLE User (
  id TEXT PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  avatar TEXT,
  role TEXT NOT NULL DEFAULT 'user',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Product (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price REAL NOT NULL,
  stock INTEGER NOT NULL DEFAULT 0,
  image TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Order (
  id TEXT PRIMARY KEY,
  orderNo TEXT UNIQUE NOT NULL,
  userId TEXT NOT NULL,
  amount REAL NOT NULL,
  status TEXT NOT NULL DEFAULT 'Pending',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id)
);

CREATE TABLE OrderItem (
  id TEXT PRIMARY KEY,
  orderId TEXT NOT NULL,
  productId TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  price REAL NOT NULL,
  FOREIGN KEY (orderId) REFERENCES Order(id),
  FOREIGN KEY (productId) REFERENCES Product(id)
);

CREATE TABLE Revenue (
  id TEXT PRIMARY KEY,
  date DATETIME NOT NULL,
  revenue REAL NOT NULL,
  profit REAL NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DailySales (
  id TEXT PRIMARY KEY,
  date DATETIME NOT NULL,
  dayName TEXT NOT NULL,
  sales REAL NOT NULL,
  orders INTEGER NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Role (
  id TEXT PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT
);

CREATE TABLE Website (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  url TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE BankAccount (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL DEFAULT 'deposit',
  bankName TEXT NOT NULL,
  accountName TEXT NOT NULL,
  accountNumber TEXT UNIQUE NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Employee (
  id TEXT PRIMARY KEY,
  fullName TEXT NOT NULL,
  websites TEXT NOT NULL,
  bankName TEXT NOT NULL,
  accountNumber TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LineToken (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  channelId TEXT NOT NULL,
  channelSecret TEXT NOT NULL,
  accessToken TEXT NOT NULL,
  websiteId TEXT,
  websiteName TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  lastUsed DATETIME,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
